### ISSUE TITLE
reloading assets after changing crt fragment shader crashes

### ISSUE THREAD

**Issue by kevinw** [unrust/unrust#49]
I edited `static/crt_fs.glsl` and hit Escape to reload it in the Postprocessing example and got a panic:

```
C:\Users\kevin\src\unrust>cargo run --example postprocessing
   Compiling unrust v0.1.1 (file:///C:/Users/kevin/src/unrust)
    Finished dev [unoptimized + debuginfo] target(s) in 2.09 secs
     Running `target\debug\examples\postprocessing.exe`
opengl 3.2.0 - Build 22.20.16.4836
shading language 1.50 - Build 22.20.16.4836
vendor Intel
sound device : Speakers (Realtek High Definition Audio) format Format { channels: 2, sample_rate: SampleRate(48000), data_type: F32 }
starting audio loop
Compiling shader file : ui_vs.glsl
Compiling shader file : ui_fs.glsl
preprocessing phong_vs.glsl...
preprocessing crt_vs.glsl...
preprocessing crt_fs.glsl...
Compiling shader file : crt_vs.glsl
Compiling shader file : crt_fs.glsl
preprocessing phong_fs.glsl...
Compiling shader file : phong_vs.glsl
Compiling shader file : phong_fs.glsl
thread 'main' panicked at 'already borrowed: BorrowMutError', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'already borrowed: BorrowMutError', libcore\result.rs:945:5
stack backtrace:
   0:     0x7ff7083610ca - std::sys::windows::backtrace::unwind_backtrace
                               at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1:     0x7ff7083708df - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2:     0x7ff7083708df - std::sys_common::backtrace::print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff70835f107 - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:205
   4:     0x7ff70835edc1 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:221
   5:     0x7ff70835f7d3 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:457
   6:     0x7ff70835f3e6 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:344
   7:     0x7ff70835f3a1 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:322
   8:     0x7ff70837672c - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:71
   9:     0x7ff7082cb0f5 - core::result::unwrap_failed<core::cell::BorrowMutError>
                               at C:\projects\rust\src\libcore\macros.rs:26
  10:     0x7ff708005ceb - core::result::Result<core::cell::RefMut<std::collections::hash::map::HashMap<core::any::TypeId, alloc::boxed::Box<Any>, std::collections::hash::map::RandomState>>, core::cell::BorrowMutError>::expect<core::cell::RefMut<std::collections::hash::map::HashMap<core::any::TypeId, alloc::boxed::Box<Any>, std::collections::hash::map::RandomState>>,core::cell::BorrowMutError>
                               at C:\projects\rust\src\libcore\result.rs:809
  11:     0x7ff707f9b97d - core::cell::RefCell<std::collections::hash::map::HashMap<core::any::TypeId, alloc::boxed::Box<Any>, std::collections::hash::map::RandomState>>::borrow_mut<std::collections::hash::map::HashMap<core::any::TypeId, alloc::boxed::Box<Any>, std::collections::hash::map::RandomState>>
                               at C:\projects\rust\src\libcore\cell.rs:816
  12:     0x7ff707fba3ce - unrust::engine::core::component_arena::ComponentArena::container<unrust::engine::render::mesh::Mesh>
                               at C:\Users\kevin\src\unrust\src\engine\core\component_arena.rs:88
  13:     0x7ff707fba0a2 - unrust::engine::core::component_arena::ComponentArena::remove<unrust::engine::render::mesh::Mesh>
                               at C:\Users\kevin\src\unrust\src\engine\core\component_arena.rs:82
  14:     0x7ff707fa876f - unrust::engine::core::game_object::{{impl}}::drop<unrust::engine::render::mesh::Mesh>
                               at C:\Users\kevin\src\unrust\src\engine\core\game_object.rs:72
  15:     0x7ff7080348ce - core::ptr::drop_in_place<unrust::engine::core::game_object::ComponentType<unrust::engine::render::mesh::Mesh>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  16:     0x7ff70802dbcb - core::ptr::drop_in_place<Component>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  17:     0x7ff707f8523d - alloc::arc::Arc<Component>::drop_slow<Component>
                               at C:\projects\rust\src\liballoc\arc.rs:517
  18:     0x7ff707f860e5 - alloc::arc::{{impl}}::drop<Component>
                               at C:\projects\rust\src\liballoc\arc.rs:969
  19:     0x7ff708021316 - core::ptr::drop_in_place<alloc::arc::Arc<Component>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  20:     0x7ff707ee7934 - alloc::vec::{{impl}}::drop<alloc::arc::Arc<Component>>
                               at C:\projects\rust\src\liballoc\vec.rs:2463
  21:     0x7ff70802eb66 - core::ptr::drop_in_place<alloc::vec::IntoIter<alloc::arc::Arc<Component>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  22:     0x7ff707fada91 - unrust::engine::core::game_object::GameObject::clear_components
                               at C:\Users\kevin\src\unrust\src\engine\core\game_object.rs:301
  23:     0x7ff707fa8ebd - unrust::engine::core::game_object::{{impl}}::drop::{{closure}}
                               at C:\Users\kevin\src\unrust\src\engine\core\game_object.rs:143
  24:     0x7ff707efdcdf - core::option::Option<alloc::rc::Rc<unrust::engine::core::scene_tree::SceneTree>>::map<alloc::rc::Rc<unrust::engine::core::scene_tree::SceneTree>,(),closure>
                               at C:\projects\rust\src\libcore\option.rs:404
  25:     0x7ff707facf43 - unrust::engine::core::game_object::{{impl}}::drop
                               at C:\Users\kevin\src\unrust\src\engine\core\game_object.rs:142
  26:     0x7ff70802868e - core::ptr::drop_in_place<unrust::engine::core::game_object::GameObject>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  27:     0x7ff7080309a6 - core::ptr::drop_in_place<core::cell::UnsafeCell<unrust::engine::core::game_object::GameObject>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  28:     0x7ff70802e74a - core::ptr::drop_in_place<core::cell::RefCell<unrust::engine::core::game_object::GameObject>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  29:     0x7ff708030d7a - core::ptr::drop_in_place<alloc::rc::RcBox<core::cell::RefCell<unrust::engine::core::game_object::GameObject>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  30:     0x7ff707f4a893 - alloc::rc::{{impl}}::drop<core::cell::RefCell<unrust::engine::core::game_object::GameObject>>
                               at C:\projects\rust\src\liballoc\rc.rs:841
  31:     0x7ff707ec59d6 - core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<unrust::engine::core::game_object::GameObject>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  32:     0x7ff707ec5670 - core::ptr::drop_in_place<postprocessing::Crt>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  33:     0x7ff707ec52e0 - core::ptr::drop_in_place<alloc::boxed::Box<Actor>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  34:     0x7ff707ec8c66 - unrust::engine::core::component_arena::ComponentContainer<alloc::boxed::Box<Actor>>::add<alloc::boxed::Box<Actor>>
                               at C:\Users\kevin\src\unrust\src\engine\core\component_arena.rs:28
  35:     0x7ff707ec8a6a - unrust::engine::core::component_arena::ComponentArena::add<alloc::boxed::Box<Actor>>
                               at C:\Users\kevin\src\unrust\src\engine\core\component_arena.rs:75
  36:     0x7ff707ecf91d - unrust::engine::core::game_object::{{impl}}::new<alloc::boxed::Box<Actor>>
                               at C:\Users\kevin\src\unrust\src\engine\core\game_object.rs:95
  37:     0x7ff707ec856d - postprocessing::{{impl}}::into_component_ptr
                               at C:\Users\kevin\src\unrust\examples\postprocessing.rs:114
  38:     0x7ff707ecf24e - unrust::engine::core::game_object::GameObject::add_component<postprocessing::Crt>
                               at C:\Users\kevin\src\unrust\src\engine\core\game_object.rs:281
  39:     0x7ff707ec6675 - postprocessing::{{impl}}::start
                               at C:\Users\kevin\src\unrust\examples\postprocessing.rs:47
  40:     0x7ff707ece967 - unrust::world::actor::Actor::start_rc<postprocessing::MainScene>
                               at C:\Users\kevin\src\unrust\src\world\actor.rs:7
  41:     0x7ff70809a9fb - unrust::world::type_watcher::{{impl}}::object_start
                               at C:\Users\kevin\src\unrust\src\world\type_watcher.rs:119
  42:     0x7ff70803d386 - unrust::world::type_watcher::Watcher::watch_step_with_new<unrust::world::type_watcher::ActorWatcher<alloc::boxed::Box<Actor>>>
                               at C:\Users\kevin\src\unrust\src\world\type_watcher.rs:57
  43:     0x7ff70809ad31 - unrust::world::type_watcher::TypeWatcher::step
                               at C:\Users\kevin\src\unrust\src\world\type_watcher.rs:157
  44:     0x7ff707f897b6 - unrust::world::world::World::step
                               at C:\Users\kevin\src\unrust\src\world\world.rs:262
  45:     0x7ff707f8ac13 - unrust::world::world::World::run_frame
                               at C:\Users\kevin\src\unrust\src\world\world.rs:344
  46:     0x7ff707fab6de - unrust::world::world::{{impl}}::event_loop::{{closure}}
                               at C:\Users\kevin\src\unrust\src\world\world.rs:356
  47:     0x7ff70809c53f - uni_app::sys::App::run<closure>
                               at C:\Users\kevin\src\unrust\uni-app\src\native_app.rs:260
  48:     0x7ff707f8ad20 - unrust::world::world::World::event_loop
                               at C:\Users\kevin\src\unrust\src\world\world.rs:355
  49:     0x7ff707ec836f - postprocessing::main
                               at C:\Users\kevin\src\unrust\examples\postprocessing.rs:224
  50:     0x7ff707ecd833 - std::rt::lang_start::{{closure}}<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  51:     0x7ff70835f2dc - std::rt::lang_start_internal::{{closure}}
                               at C:\projects\rust\src\libstd\rt.rs:59
  52:     0x7ff70835f2dc - std::panicking::try::do_call<closure,i32>
                               at C:\projects\rust\src\libstd\panicking.rs:304
  53:     0x7ff708373d01 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  54:     0x7ff708360c72 - std::panicking::try
                               at C:\projects\rust\src\libstd\panicking.rs:283
  55:     0x7ff708360c72 - std::panic::catch_unwind
                               at C:\projects\rust\src\libstd\panic.rs:361
  56:     0x7ff708360c72 - std::rt::lang_start_internal
                               at C:\projects\rust\src\libstd\rt.rs:58
  57:     0x7ff707ecd803 - std::rt::lang_start<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  58:     0x7ff707ec8616 - main
  59:     0x7ff70838543f - invoke_main
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  60:     0x7ff70838543f - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  61:     0x7ff961b41fe3 - BaseThreadInitThunk
  62:     0x7ff96390f060 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\examples\postprocessing.exe` (exit code: 3221225501)
```

**Comment by edwin0cheng** [comment]
Thanks for the report. It turn outs there are some bugs in newly added ComponentArena. It should be fixed in master.

**Comment by kevinw** [comment]
The new fixes worked great for me, thanks!
